#version 450

layout(binding = 0, rgba8) uniform image2D canvasImage;
layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(push_constant) uniform PushData {
	vec4 Colour;
	vec2 MousePos;
    int Shape;
	float Radius;
    bool Antialiased;
} PushConstants;

float sdCircle(vec2 pos, float radius)
{
    return length(pos) - radius;
}

float sdSquare(vec2 pos, float radius)
{
    return length(min(pos, -radius) + max(pos, radius));
}

float sdTriangle(vec2 pos, float radius)
{
    const float k = sqrt(3.0);

    pos.x = abs(pos.x) - radius;
    pos.y = pos.y + radius / k;

    if (pos.x + k * pos.y > 0.0)
    {
        pos = vec2(pos.x - k * pos.y, -k * pos.x - pos.y) / 2.0;
    }

    pos.x -= clamp(pos.x, -2.0 * radius, 0.0);
    return -length(pos) * sign(pos.y);
}

void main()
{
    ivec2 pixelCoords = ivec2(gl_GlobalInvocationID.xy);

    vec2 pos = pixelCoords - PushConstants.MousePos;
    float dist = 1e10;

    if (PushConstants.Shape == 0) dist = sdCircle(pos, PushConstants.Radius);
    else if (PushConstants.Shape == 1) dist = sdSquare(pos, PushConstants.Radius);
    else if (PushConstants.Shape == 2) dist = sdTriangle(pos, PushConstants.Radius);

    if (PushConstants.Antialiased)
    {
        float aa = 2.0;
        float alpha = 1.0 - smoothstep(-aa, aa, dist);

        if (alpha > 0.0)
        {
            vec4 oldColour = imageLoad(canvasImage, pixelCoords);
            vec4 colour = mix(oldColour, PushConstants.Colour, alpha);

            imageStore(canvasImage, pixelCoords, colour);
        }
    }
    else
    {
        if (dist <= 0.0)
        {
            imageStore(canvasImage, pixelCoords, PushConstants.Colour);
        }
    }
}
