#version 450

layout(binding = 0, rgba8) uniform writeonly image2D canvasImage;
layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

void main() {
    // Get the integer coords of the current pixel
    ivec2 pixelCoords = ivec2(gl_GlobalInvocationID.xy);

    // Get the total size of the image
    ivec2 size = imageSize(canvasImage);

    float u = float(pixelCoords.x) / float(size.x - 1);
    float v = float(pixelCoords.y) / float(size.y - 1);

    vec4 color = vec4(u, v, 0.0, 1.0);
    imageStore(canvasImage, pixelCoords, color);
}
