#version 450

layout(binding = 0, rgba8) uniform writeonly image2D canvasImage;
layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(push_constant) uniform PushData {
	vec4 Colour;
} PushConstants;

void main() {
    // Get the integer coords of the current pixel
    ivec2 pixelCoords = ivec2(gl_GlobalInvocationID.xy);

    vec4 colour = PushConstants.Colour;
    imageStore(canvasImage, pixelCoords, colour);
}
